import type { Project } from "@/lib/schema";

/**
 * Real Madane Design Workshop portfolio, generated from the studio's project
 * catalogue (MADANE_SORTED/_CATALOG/projects.json). Images live under
 * /public/assets/projects/<slug>/. NOTE: `year` is a placeholder spread (not
 * present in the source data), confirm with the studio before publishing.
 */
export const projects: Project[] = [
  {
    slug: "rudra-villa",
    name: "Rudra Villa",
    type: "Architecture",
    client: "Private residence",
    location: "Alibag, Maharashtra",
    city: "Alibag",
    year: 2025,
    area: "18,000 sq.ft.",
    status: "Ongoing",
    scope: ["Architecture", "Interiors and landscape", "Design and execution"],
    services: ["Architecture", "Interior"],
    cover: "/assets/projects/rudra-villa/cover.jpg",
    coverAlt: "Front elevation render of the villa with perforated terracotta jaali facade, flat-roof massing and a car in the porte-cochere.",
    screenVideo: "/assets/video/homepage-hero.mp4",
    narrative: {
      brief: "An 18,000 sq.ft. weekend villa in Alibag where contemporary architecture meets Indian craft, jaali screens, brass accents and sea views across every room.",
      site: "Residential commission in Alibag, Maharashtra. Ongoing.",
      response: "Rudra Villa is an ongoing 18,000 sq.ft. weekend retreat in Alibag, with Madane Design Workshop handling architecture, interiors and landscape end to end. The 3D-rendered scheme pairs a clean modern shell, flat-roof massing, perforated terracotta jaali facade, full-height glazing, with warm Indian detailing: a sunburst metal entry door, deity wall art, patterned tile floors, swing seats and a pool court. Bedrooms, lounges, a games room and multiple themed bathrooms all open toward greenery and the sea horizon.",
    },
    gallery: [
      { src: "/assets/projects/rudra-villa/g01.jpg", alt: "Swimming pool court with timber pergola cabana, water spouts and a sculptural mermaid figure amid lush planting.", span: "full" },
      { src: "/assets/projects/rudra-villa/g02.jpg", alt: "Grand entry portal with a dramatic circular sunburst metal door framed by stone walls.", span: "half" },
      { src: "/assets/projects/rudra-villa/g03.jpg", alt: "Games room with a full-size pool table under an exposed timber-truss roof and tropical botanical wall art.", span: "half" },
      { src: "/assets/projects/rudra-villa/g04.jpg", alt: "Serene master suite under a timber-truss ceiling with carved poster bed, arched niches and sea-facing balcony.", span: "wide" },
      { src: "/assets/projects/rudra-villa/g05.jpg", alt: "Double-height living hall with sculptural wall discs, a sunken seating pit and views to the rear lounge.", span: "half" },
      { src: "/assets/projects/rudra-villa/g06.jpg", alt: "Stair and lift core with a carved Buddha-face feature wall, water body and floating treads beside a green court.", span: "tall" },
      { src: "/assets/projects/rudra-villa/g07.jpg", alt: "Open-plan dining area with eight-seat table, ceiling fans and full-height glazing to a landscaped court.", span: "half" },
      { src: "/assets/projects/rudra-villa/g08.jpg", alt: "Family living room with concrete feature wall, mounted TV, layered seating and a bold figurative artwork.", span: "wide" },
      { src: "/assets/projects/rudra-villa/g09.jpg", alt: "Modern kitchen with marble island, breakfast bar stools and panoramic windows over the skyline.", span: "full" },
      { src: "/assets/projects/rudra-villa/g10.jpg", alt: "Powder room with floral mosaic feature wall, dark tiling and brass fixtures.", span: "full" },
    ],
    featured: true,
    order: 0,
    seo: { title: "Rudra Villa, Architecture", description: "An 18,000 sq.ft. weekend villa in Alibag where contemporary architecture meets Indian craft, jaali screens, brass accents and sea views across every room." },
  },
  {
    slug: "sun-petrochemicals-pvt-ltd-corporate-office",
    name: "Sun Petrochemicals Pvt. Ltd., Corporate Office",
    type: "Interior",
    client: "Sun Petrochemicals Pvt. Ltd.",
    location: "India",
    city: "India",
    year: 2024,
    area: "",
    status: "completed",
    scope: ["Commercial interior fit-out", "Reception", "Lobby", "Cabins", "Meeting/boardrooms"],
    services: ["Interior", "Turnkey"],
    cover: "/assets/projects/sun-petrochemicals-pvt-ltd-corporate-office/cover.jpg",
    coverAlt: "Reception with glossy black desk and illuminated 'sun Petrochemicals' logo on a warm tan wall, lounge seating beyond.",
    narrative: {
      brief: "A crisp, light-filled corporate office for Sun Petrochemicals, balancing clean white minimalism with warm wood, terracotta accents and a polished branded reception.",
      site: "Corporate office (petrochemical / industrial) commission in India. completed.",
      response: "A full corporate-office fit-out for Sun Petrochemicals Pvt. Ltd., anchored by a glossy black reception desk carrying the illuminated \"sun Petrochemicals\" logo against a warm tan feature wall. The palette pairs marble-effect flooring and bright white minimalist ceilings with wood-panelled cabins, terracotta curved volumes and frosted-glass meeting rooms. The programme spans reception and lounge, a marble lift lobby with a small shrine, multiple meeting and boardrooms, open and cubicle workstations, executive cabins and a playful branded cafeteria.",
    },
    gallery: [
      { src: "/assets/projects/sun-petrochemicals-pvt-ltd-corporate-office/g01.jpg", alt: "Boardroom with long black table, tan leather chairs, circular cove ceiling and framed abstract art.", span: "full" },
      { src: "/assets/projects/sun-petrochemicals-pvt-ltd-corporate-office/g02.jpg", alt: "Cafeteria with olive coffered ceiling, terrazzo floor, yellow chairs and graphic 'sun' branded wall.", span: "half" },
      { src: "/assets/projects/sun-petrochemicals-pvt-ltd-corporate-office/g03.jpg", alt: "Bright waiting lounge under a layered circular ceiling cove, with frosted-glass meeting rooms lining the corridor.", span: "half" },
      { src: "/assets/projects/sun-petrochemicals-pvt-ltd-corporate-office/g04.jpg", alt: "Marble-clad lift lobby with dark stone elevator surrounds and a small illuminated shrine niche.", span: "wide" },
      { src: "/assets/projects/sun-petrochemicals-pvt-ltd-corporate-office/g05.jpg", alt: "Wood-lined breakout alcove with a curved canopy and dark accent chairs along a circulation spine.", span: "half" },
      { src: "/assets/projects/sun-petrochemicals-pvt-ltd-corporate-office/g06.jpg", alt: "Open-plan workstation hall with white benching desks, wall-mounted screen and city views through ribbon windows.", span: "tall" },
      { src: "/assets/projects/sun-petrochemicals-pvt-ltd-corporate-office/g07.jpg", alt: "Grey cubicle workstation area with grid ceiling and overhead storage units.", span: "half" },
      { src: "/assets/projects/sun-petrochemicals-pvt-ltd-corporate-office/g08.jpg", alt: "Executive cabin with white desk, patterned wood feature wall, sofa and a sculptural pendant light.", span: "wide" },
      { src: "/assets/projects/sun-petrochemicals-pvt-ltd-corporate-office/g09.jpg", alt: "Compact meeting room with wood-panelled wall, white table, tan chairs and wall-mounted display.", span: "full" },
    ],
    featured: true,
    order: 1,
    seo: { title: "Sun Petrochemicals Pvt. Ltd., Corporate Office, Interior", description: "A crisp, light-filled corporate office for Sun Petrochemicals, balancing clean white minimalism with warm wood, terracotta accents and a polished branded r" },
  },
  {
    slug: "akasa-kolkata",
    name: "Akasa, Kolkata",
    type: "Interior",
    client: "Akasa",
    location: "Kolkata, West Bengal",
    city: "Kolkata",
    year: 2023,
    area: "",
    status: "Completed",
    scope: ["Commercial interior fit-out: reception", "Private cabins", "Meeting and conference rooms", "Open workstations", "Breakout cafeteria"],
    services: ["Interior", "Turnkey"],
    cover: "/assets/projects/akasa-kolkata/cover.jpg",
    coverAlt: "Reception viewed through bronze-fluted glazed doors, with backlit AKASA signage and an inverted black-marble desk.",
    narrative: {
      brief: "A polished Akasa managed-office and coworking floor in Kolkata where a dramatic inverted-marble reception sets the tone for cabins, meeting rooms and a playful cafe.",
      site: "Coworking commission in Kolkata, West Bengal. Completed.",
      response: "Akasa Kolkata is a completed commercial-interior fit-out for a managed-office / coworking operator, anchored by a striking reception with an inverted black-marble desk, backlit AKASA signage and bronze-fluted glazed entry doors. The floor mixes private cabins and tan-leather conference rooms with open workstation suites, frosted-glass partitions, geometric carpet and timber-batten ceilings, plus a velvet upholstered breakout nook. A bright cafeteria with bold abstract wall graphics, curved-timber ceiling and warm pendant lighting rounds out the amenity offer.",
    },
    gallery: [
      { src: "/assets/projects/akasa-kolkata/g01.jpg", alt: "Boardroom with long table, tan-leather Eames-style chairs, acoustic panels and warm timber ceiling.", span: "full" },
      { src: "/assets/projects/akasa-kolkata/g02.jpg", alt: "Corridor breakout nook with a sculpted blue velvet upholstered bench and barn-door glazed cabins.", span: "half" },
      { src: "/assets/projects/akasa-kolkata/g03.jpg", alt: "Cafe seating with bar counter, warm pendants, sculpted timber ceiling and colourful mural backdrop.", span: "half" },
      { src: "/assets/projects/akasa-kolkata/g04.jpg", alt: "Training / presentation room with tan-leather chairs, timber-slat ceiling and wall-mounted screen.", span: "wide" },
      { src: "/assets/projects/akasa-kolkata/g05.jpg", alt: "Compact private cabin with desk, orange task chairs and a cream sofa against white panelled walls.", span: "half" },
      { src: "/assets/projects/akasa-kolkata/g06.jpg", alt: "Small meeting room with grey table, white mesh chairs and wall-mounted display on a dark panel.", span: "tall" },
      { src: "/assets/projects/akasa-kolkata/g07.jpg", alt: "Workstation suite with white desks, green mesh chairs, storage cabinetry and frosted-glass partition.", span: "half" },
      { src: "/assets/projects/akasa-kolkata/g08.jpg", alt: "Cafeteria with bold abstract wall graphic, curved-timber ceiling, pendant lights and timber chairs.", span: "wide" },
    ],
    featured: true,
    order: 2,
    seo: { title: "Akasa, Kolkata, Interior", description: "A polished Akasa managed-office and coworking floor in Kolkata where a dramatic inverted-marble reception sets the tone for cabins, meeting rooms and a pla" },
  },
  {
    slug: "semac-consultants-pvt-ltd-office",
    name: "Semac Consultants Pvt. Ltd. Office",
    type: "Interior",
    client: "Semac Consultants Pvt. Ltd.",
    location: "India",
    city: "India",
    year: 2022,
    area: "",
    status: "Completed",
    scope: ["Corporate office interior fit-out: reception", "Open workstations", "Breakout and circulation zones", "Storage and pooja niche"],
    services: ["Interior", "Turnkey"],
    cover: "/assets/projects/semac-consultants-pvt-ltd-office/cover.jpg",
    coverAlt: "Reception viewed through glass doors, with the backlit white sculptural desk and SEMAC logo on a curved timber backwall flanked by green velvet sofas.",
    narrative: {
      brief: "A warm, India-themed corporate office for Semac Consultants where arched timber portals, epic murals and curved workstations frame a high-rise city skyline.",
      site: "Engineering consultancy commission in India. Completed.",
      response: "A completed corporate office interior for engineering consultancy Semac Consultants Pvt. Ltd., set on an upper floor with sweeping high-rise city views. The design layers warm wood-tone arches, green velvet reception seating and curved bamboo-topped workstation clusters against dramatic Indian mythological murals, Devanagari wall quotes and a jewel-toned pooja niche. Exposed services ceilings, track lighting and a muted carpet palette give it a contemporary yet culturally rooted character.",
    },
    gallery: [
      { src: "/assets/projects/semac-consultants-pvt-ltd-office/g01.jpg", alt: "Symmetrical curved workstation pods framing a central carpeted aisle, bracketed by glowing riverscape murals.", span: "full" },
      { src: "/assets/projects/semac-consultants-pvt-ltd-office/g02.jpg", alt: "Sweeping curved workstation island beside a dramatic golden mythological mural, overlooking high-rise towers.", span: "half" },
      { src: "/assets/projects/semac-consultants-pvt-ltd-office/g03.jpg", alt: "Open-plan workstation zone at dusk, curved bamboo desks wrapping around planted trees with the city skyline through full-height glazing.", span: "half" },
      { src: "/assets/projects/semac-consultants-pvt-ltd-office/g04.jpg", alt: "Reception lounge with green velvet seating and a Devanagari Bhagavad Gita quote spotlit on the wall beside the fluted desk.", span: "wide" },
      { src: "/assets/projects/semac-consultants-pvt-ltd-office/g05.jpg", alt: "Arched timber portal framing the office depth, flanked by vivid night-riverscape murals above desk runs.", span: "half" },
      { src: "/assets/projects/semac-consultants-pvt-ltd-office/g06.jpg", alt: "Workstation cluster with a large epic-battle mural column and illuminated riverscape walls under linear lighting.", span: "tall" },
      { src: "/assets/projects/semac-consultants-pvt-ltd-office/g07.jpg", alt: "Grey triangular cubby storage units against wood paneling, with arched openings leading into adjacent work areas.", span: "half" },
      { src: "/assets/projects/semac-consultants-pvt-ltd-office/g08.jpg", alt: "View through a timber arch to grid storage shelving and an informal timber chair seating nook.", span: "wide" },
      { src: "/assets/projects/semac-consultants-pvt-ltd-office/g09.jpg", alt: "Jewel-toned pooja niche with a pink and blue Rajasthani-style arch motif framed within a tall timber portal.", span: "full" },
    ],
    featured: true,
    order: 3,
    seo: { title: "Semac Consultants Pvt. Ltd. Office, Interior", description: "A warm, India-themed corporate office for Semac Consultants where arched timber portals, epic murals and curved workstations frame a high-rise city skyline" },
  },
  {
    slug: "john-cockerill-office-aurum-parc-ghansoli",
    name: "John Cockerill Office, Aurum Parc Ghansoli",
    type: "Interior",
    client: "John Cockerill",
    location: "Aurum Parc, Ghansoli, Navi Mumbai",
    city: "Navi Mumbai",
    year: 2021,
    area: "Large-format single-floor office plate (open-plan workstations + conference + reception)",
    status: "Design / proposal stage (3D renders)",
    scope: ["Corporate office interior fit-out: reception", "Conference cabins", "Large open-plan workstation floor", "Breakout/collaboration zones", "Lockers and pantry"],
    services: ["Interior", "Turnkey"],
    cover: "/assets/projects/john-cockerill-office-aurum-parc-ghansoli/cover.jpg",
    coverAlt: "Reception with John Cockerill logo wall, rust banquettes and a glass meeting room beyond.",
    narrative: {
      brief: "A bright, biophilic corporate workplace for engineering group John Cockerill at Aurum Parc, Ghansoli, balancing vast open-plan workstations with green-and-blue collaboration pods.",
      site: "Corporate / engineering (industrial) commission in Aurum Parc, Ghansoli, Navi Mumbai. Design / proposal stage (3D renders).",
      response: "A full corporate office fit-out for the engineering group John Cockerill at Aurum Parc in Ghansoli, Navi Mumbai. The scheme pairs a clean white-and-charcoal reception carrying the John Cockerill logo with expansive open-plan workstation floors wrapped in floor-to-ceiling glazing and hill views, punctuated by green and blue acoustic pods, planter screens and brand-history graphic walls. Drum and dome pendants, exposed services ceilings, and breakout banquettes give the engineering workplace a warm, biophilic, collaborative character. All assets are photorealistic 3D renders from the design stage.",
    },
    gallery: [
      { src: "/assets/projects/john-cockerill-office-aurum-parc-ghansoli/g01.jpg", alt: "Expansive open-plan workstation floor with green accent column, planter spines and panoramic glazing.", span: "full" },
      { src: "/assets/projects/john-cockerill-office-aurum-parc-ghansoli/g02.jpg", alt: "Sunlit corner workstation cluster with red-flowering planters, green column and sweeping window views.", span: "half" },
      { src: "/assets/projects/john-cockerill-office-aurum-parc-ghansoli/g03.jpg", alt: "Conference cabin with blue acoustic-panel wall, framed product graphics and a long boardroom table open to the workfloor.", span: "half" },
      { src: "/assets/projects/john-cockerill-office-aurum-parc-ghansoli/g04.jpg", alt: "Breakout collaboration bar with planter-topped counter, swivel stools and green/blue acoustic columns.", span: "wide" },
      { src: "/assets/projects/john-cockerill-office-aurum-parc-ghansoli/g05.jpg", alt: "Twin conference rooms with oval ceiling rafts and blue panelled feature walls, shown as a split/mirrored render.", span: "half" },
      { src: "/assets/projects/john-cockerill-office-aurum-parc-ghansoli/g06.jpg", alt: "Workfloor edge with a blue Mercury Marine brand-history timeline graphic wall behind the desks.", span: "tall" },
      { src: "/assets/projects/john-cockerill-office-aurum-parc-ghansoli/g07.jpg", alt: "Open workstations with a teal focus booth and green planter screens dividing the floor.", span: "half" },
      { src: "/assets/projects/john-cockerill-office-aurum-parc-ghansoli/g08.jpg", alt: "Collaboration table under drum pendants beside a blue/green acoustic pod with mountain views.", span: "wide" },
      { src: "/assets/projects/john-cockerill-office-aurum-parc-ghansoli/g09.jpg", alt: "Activity-based work zone mixing a meeting table, orange-lit drum pendants and an upholstered lounge sofa.", span: "full" },
      { src: "/assets/projects/john-cockerill-office-aurum-parc-ghansoli/g10.jpg", alt: "Wide biophilic workfloor lined with flowering planters, low workstations and panoramic glazing.", span: "full" },
    ],
    featured: true,
    order: 4,
    seo: { title: "John Cockerill Office, Aurum Parc Ghansoli, Interior", description: "A bright, biophilic corporate workplace for engineering group John Cockerill at Aurum Parc, Ghansoli, balancing vast open-plan workstations with green-and-" },
  },
  {
    slug: "kushal-wallstreet",
    name: "Kushal Wallstreet",
    type: "Architecture",
    client: "Kushal",
    location: "Pune, India",
    city: "India",
    year: 2020,
    area: "Gr + 10 structure",
    status: "Under construction (2nd floor in progress)",
    scope: ["Architecture and facade development"],
    services: ["Architecture"],
    cover: "/assets/projects/kushal-wallstreet/cover.jpg",
    coverAlt: "Dusk three-quarter street view of the illuminated glass-and-fin office tower with adjacent low-rise context and traffic light trails.",
    narrative: {
      brief: "A Gr+10 commercial office tower in Pune wrapped in vertical metallic fins, full-height glazing and stacked sky-gardens, branded around a Wall Street bull motif.",
      site: "Commercial office commission in Pune, India. Under construction (2nd floor in progress).",
      response: "Kushal Wallstreet is a ground-plus-ten storey commercial office building in Pune, designed as a sleek glazed tower with vertical metallic fins for solar shading and a dynamic facade. Renders show a finance-themed retail and office podium, complete with a Wall Street charging-bull sculpture and prominent \"Kushal Wallstreet\" signage, topped by stacked planted terraces and corporate tenant frontages. The scheme is currently in construction, with architectural and facade development as the core scope.",
    },
    gallery: [
      { src: "/assets/projects/kushal-wallstreet/g01.jpg", alt: "Twilight street-level hero of the tower's corner, glowing metallic fins and the finance-themed retail podium with the charging-bull branding.", span: "full" },
      { src: "/assets/projects/kushal-wallstreet/g02.jpg", alt: "Daytime upward corner view showing the full tower, podium glazing and the 'Kushal Wallstreet' entrance signage with the Wall Street bull mural.", span: "half" },
      { src: "/assets/projects/kushal-wallstreet/g03.jpg", alt: "Frontal elevation render of the full glazed monobloc with mid-height planted terraces and rooftop signage against the city skyline.", span: "half" },
      { src: "/assets/projects/kushal-wallstreet/g04.jpg", alt: "Pedestrian-level view along the podium showing tenant frontages (Tommy, Piaget, Verte, Finance) behind a green-clad arcade.", span: "wide" },
    ],
    featured: true,
    order: 5,
    seo: { title: "Kushal Wallstreet, Architecture", description: "A Gr+10 commercial office tower in Pune wrapped in vertical metallic fins, full-height glazing and stacked sky-gardens, branded around a Wall Street bull m" },
  },
  {
    slug: "lodha-1-office",
    name: "Lodha 1 Office",
    type: "Interior",
    client: "Lodha",
    location: "India",
    city: "India",
    year: 2019,
    area: "",
    status: "design / visualization",
    scope: ["Interior design and fit-out of corporate office (workstations", "Conference cabin", "Reception", "Mandir", "Circulation)"],
    services: ["Interior", "Turnkey"],
    cover: "/assets/projects/lodha-1-office/cover.jpg",
    coverAlt: "Signature wide view: flowing LED light-lines, burgundy chairs, marble desks and arched brass cabin under a wave ceiling.",
    narrative: {
      brief: "A sculptural corporate office where flowing LED light-trails, arched brass portals and marble worktops turn an open floorplate into a fluid, premium workspace.",
      site: "Corporate office commission. design / visualization.",
      response: "A fully-rendered commercial office interior for Lodha, presented in two design directions: a teal-and-walnut scheme and an \"optimized\" variant using burgundy seating with dramatic veined-marble feature walls. The design language centres on ribbon-like white LED lines that sweep across dark flooring, curved arched openings, brass-mesh partition screens, slatted/acoustic ceilings and marble-topped workstations, with a Ganesh mandir niche anchoring the entry. All assets are CGI renders plus one top-down plan; no built photography or external branding is present.",
    },
    gallery: [
      { src: "/assets/projects/lodha-1-office/g01.jpg", alt: "Open workstation cluster with marble desk, teal task chairs and arched portals framing the conference cabin beyond.", span: "full" },
      { src: "/assets/projects/lodha-1-office/g02.jpg", alt: "Optimized open office across a veined-marble counter, acoustic wave ceiling and brass-screened meeting pod.", span: "half" },
      { src: "/assets/projects/lodha-1-office/g03.jpg", alt: "Conference cabin with a black-marble boardroom table, tan leather chairs, molecule-style linear chandelier and walnut wall.", span: "half" },
      { src: "/assets/projects/lodha-1-office/g04.jpg", alt: "Entry/reception view with a sculpted brass desk and white LED light-lines curving across the dark floor.", span: "wide" },
      { src: "/assets/projects/lodha-1-office/g05.jpg", alt: "Arched lounge with curved bouclé sofa, niche shelving and a Ganesh mandir, opening to the meeting room (teal scheme).", span: "half" },
      { src: "/assets/projects/lodha-1-office/g06.jpg", alt: "Mandir niche with Ganesh idol on marble plinth beside an arched view into the open office (teal scheme).", span: "tall" },
      { src: "/assets/projects/lodha-1-office/g07.jpg", alt: "Wide-angle workspace with slatted wood ceiling, curved glazing and the conference cabin visible through a brass screen.", span: "half" },
      { src: "/assets/projects/lodha-1-office/g08.jpg", alt: "Workstation pod under sculpted oval light fixtures with marble desk, teal chairs and walnut storage wall.", span: "wide" },
      { src: "/assets/projects/lodha-1-office/g09.jpg", alt: "Desk cluster with potted olive trees, ribbed ceiling and the meeting cabin framed through an arched opening.", span: "full" },
      { src: "/assets/projects/lodha-1-office/g10.jpg", alt: "Optimized conference cabin: black-marble table, tan chairs and a dramatic veined-marble feature wall (near-duplicate viewpoint).", span: "full" },
    ],
    featured: true,
    order: 6,
    seo: { title: "Lodha 1 Office, Interior", description: "A sculptural corporate office where flowing LED light-trails, arched brass portals and marble worktops turn an open floorplate into a fluid, premium worksp" },
  },
  {
    slug: "raymond-office",
    name: "Raymond Office",
    type: "Interior",
    client: "Raymond",
    location: "India",
    city: "India",
    year: 2018,
    area: "",
    status: "completed",
    scope: ["Corporate office interior fit-out: reception", "Boardrooms", "Meeting rooms and breakout lounge"],
    services: ["Interior", "Turnkey"],
    cover: "/assets/projects/raymond-office/cover.jpg",
    coverAlt: "Reception with vibrant vertical multi-colour striped feature wall, red neon brand logo, illuminated front desk and concentric linear ceiling profile.",
    narrative: {
      brief: "A polished corporate office for Raymond, anchored by a bold multi-colour striped reception and sculptural boardroom ceilings.",
      site: "Corporate office commission. completed.",
      response: "Corporate office interior fit-out for the apparel and textile brand Raymond, photographed on completion. The scheme pairs a vibrant vertical multi-colour striped feature wall and red neon logo at reception with refined wood-panelled and pixel-graphic boardrooms. Sculptural baffle and recessed-trench lighting, glass-partitioned cabins and a soft-toned breakout lounge round out the space.",
    },
    gallery: [
      { src: "/assets/projects/raymond-office/g01.jpg", alt: "Large meeting room featuring a sculptural wave-form baffle ceiling above a long table and a blue pixel-pattern acoustic feature wall.", span: "full" },
      { src: "/assets/projects/raymond-office/g02.jpg", alt: "Boardroom with long white conference table, executive black leather chairs, warm wood-panelled wall and grid-recessed linear lighting.", span: "half" },
      { src: "/assets/projects/raymond-office/g03.jpg", alt: "Breakout lounge with terracotta-toned glass cabin, wood-floor inset seating zone, planters and a curved floating ceiling with cove lighting.", span: "half" },
    ],
    featured: true,
    order: 7,
    seo: { title: "Raymond Office, Interior", description: "A polished corporate office for Raymond, anchored by a bold multi-colour striped reception and sculptural boardroom ceilings." },
  },
  {
    slug: "hero-electric-manufacturing-facility",
    name: "Hero Electric Manufacturing Facility",
    type: "Architecture",
    client: "Hero Electric",
    location: "Ludhiana, Punjab, India",
    city: "India",
    year: 2017,
    area: "Ground + 1 structure",
    status: "Under construction",
    scope: ["Architecture"],
    services: ["Architecture"],
    cover: "/assets/projects/hero-electric-manufacturing-facility/cover.jpg",
    coverAlt: "Corner approach render of the Hero Electric facility showing the two-storey panelised facade, glazed upper office volume and circular red logo, with landscaped palms and a sports car at the entry.",
    narrative: {
      brief: "A bold industrial facility for Hero Electric in Ludhiana, where crisp panelised facades meet a sweeping red branded canopy.",
      site: "Industrial commission in Ludhiana, Punjab, India. Under construction.",
      response: "Architectural design for a Ground + 1 manufacturing and office facility for Hero Electric in Ludhiana, Punjab. The renders show a long, clean-lined structure clad in light precast-style panels punctuated by tall black vertical fenestration, anchored by a dramatic red angular canopy and prominent Hero Electric branding. The complex houses machinery and offices and is currently under construction.",
    },
    gallery: [
      { src: "/assets/projects/hero-electric-manufacturing-facility/g01.jpg", alt: "Street-level perspective along the long panelised elevation, with rhythmic black vertical glazing leading the eye to the cantilevered red Hero Electric canopy.", span: "full" },
      { src: "/assets/projects/hero-electric-manufacturing-facility/g02.jpg", alt: "Wide three-quarter render of the full massing under a bright sky, showing the gabled volume, the red angular entrance canopy and the open ground-floor frontage.", span: "half" },
    ],
    featured: true,
    order: 8,
    seo: { title: "Hero Electric Manufacturing Facility, Architecture", description: "A bold industrial facility for Hero Electric in Ludhiana, where crisp panelised facades meet a sweeping red branded canopy." },
  },
  {
    slug: "ufo-moviez-cinema-complex",
    name: "UFO Moviez Cinema Complex",
    type: "Architecture",
    client: "UFO Moviez / NOVA Cinemaz",
    location: "Gujarat, India",
    city: "India",
    year: 2025,
    area: "",
    status: "Design stage",
    scope: ["Architecture and interior design for a 3-screen theatre complex"],
    services: ["Architecture", "Interior"],
    cover: "/assets/projects/ufo-moviez-cinema-complex/cover.jpg",
    coverAlt: "NOVA Cinemaz lobby render with reflective black floor, circuit-line ceiling, poster wall and a row of red sofas.",
    narrative: {
      brief: "A bold 3-screen cinema complex wrapping a mosaic-coloured facade around dramatic red-lit auditoriums and a lounge-style foyer.",
      site: "Hospitality commission in Gujarat, India. Design stage.",
      response: "Design-stage proposal for a three-screen multiplex in Gujarat, developed for UFO Moviez under the NOVA Cinemaz brand. The renders show a two-storey building topped by a vivid pixelated multi-colour facade band, paired with auditorium interiors driven by sculptural red light-lines and a sleek black-floored lobby lined with backlit film posters and a snack counter. The scheme covers both the building architecture and the cinema interiors.",
    },
    gallery: [
      { src: "/assets/projects/ufo-moviez-cinema-complex/g01.jpg", alt: "Three-quarter massing render of the two-storey cinema with its vivid mosaic-coloured upper facade and landscaped entry.", span: "full" },
      { src: "/assets/projects/ufo-moviez-cinema-complex/g02.jpg", alt: "Cinema auditorium render with red recliner seating and sculptural red light-line accents wrapping the acoustic walls and ceiling.", span: "half" },
      { src: "/assets/projects/ufo-moviez-cinema-complex/g03.jpg", alt: "UFO-branded foyer with backlit film posters, illuminated ceiling rings, red lounge seating and a glowing concession display.", span: "half" },
      { src: "/assets/projects/ufo-moviez-cinema-complex/g04.jpg", alt: "Screen-facing view of an auditorium framed by curving red neon light-lines against grey acoustic panelling.", span: "wide" },
      { src: "/assets/projects/ufo-moviez-cinema-complex/g05.jpg", alt: "Front elevation showing the multiplex topped by a pixelated multi-colour facade band over a recessed grey base.", span: "half" },
      { src: "/assets/projects/ufo-moviez-cinema-complex/g06.jpg", alt: "Corner exterior massing view emphasising the floating coloured-tile volume above a white cantilevered base.", span: "tall" },
    ],
    featured: true,
    order: 9,
    seo: { title: "UFO Moviez Cinema Complex, Architecture", description: "A bold 3-screen cinema complex wrapping a mosaic-coloured facade around dramatic red-lit auditoriums and a lounge-style foyer." },
  },
  {
    slug: "advait-126-136",
    name: "Advait 126 + 136",
    type: "Architecture",
    client: "Advait",
    location: "Mumbai, India",
    city: "India",
    year: 2024,
    area: "Ground + 17 storeys",
    status: "Under construction (plinth in progress)",
    scope: ["Architecture", "Landscape and interiors", "Architectural planning and detailing"],
    services: ["Architecture", "Interior"],
    cover: "/assets/projects/advait-126-136/cover.jpg",
    coverAlt: "Twin towers 126 and 136 shown side by side against a bright blue sky, capturing the full development at a glance.",
    narrative: {
      brief: "A pair of Ground+17 residential towers in Mumbai, clad in warm earthy tones with crisp vertical fins and slim balcony lines.",
      site: "Residential commission in Mumbai, India. Under construction (plinth in progress).",
      response: "Advait 126 + 136 is a twin high-rise residential development in Mumbai, designed as two slender Ground+17 towers identified by their \"126\" and \"136\" facade numbering. The 3D renders show a restrained contemporary language: tall vertical fins crowning the buildings, warm beige-and-brown stone-toned cladding, and stacked balconies framed by clean horizontal banding. The project is currently in the construction stage with the plinth in progress, and Madane's scope covers architecture, landscape and interiors including architectural planning and detailing.",
    },
    gallery: [
      { src: "/assets/projects/advait-126-136/g01.jpg", alt: "Street-level render of the 126 tower with its crowning vertical fins, warm cladding and stacked balconies.", span: "full" },
      { src: "/assets/projects/advait-126-136/g02.jpg", alt: "Angled exterior view of the tower set among neighbouring high-rises, showing the slim massing and balcony rhythm.", span: "half" },
    ],
    featured: false,
    order: 10,
    seo: { title: "Advait 126 + 136, Architecture", description: "A pair of Ground+17 residential towers in Mumbai, clad in warm earthy tones with crisp vertical fins and slim balcony lines." },
  },
  {
    slug: "akasa-noida",
    name: "Akasa, Noida",
    type: "Interior",
    client: "Pooja Fin Lease",
    location: "Noida, Uttar Pradesh",
    city: "Noida",
    year: 2023,
    area: "",
    status: "Mixed, built spaces photographed, some areas shown as design renders",
    scope: ["Corporate office interior fit-out", "Reception lobby", "Cabins", "Meeting/boardrooms", "Open workstations"],
    services: ["Interior", "Turnkey"],
    cover: "/assets/projects/akasa-noida/cover.jpg",
    coverAlt: "Double-height reception lobby render with curved bronze desk, 'Pooja Fin Lease' branding, lounge seating and full-height curtain-wall glazing.",
    narrative: {
      brief: "A corporate office fit-out in Noida for NBFC Pooja Fin Lease, pairing a double-height marble lobby with warm, material-rich boardrooms and bright open workspaces.",
      site: "NBFC commission in Noida, Uttar Pradesh. Mixed, built spaces photographed, some areas shown as design renders.",
      response: "Commercial-interior project for Pooja Fin Lease at Akasa, Noida, spanning a double-height reception lobby, executive cabins, multiple meeting and boardrooms, and open workstation areas. The package combines completed-site photography (marble conference room, timber-and-fabric boardroom, teal and turquoise workstation bays) with photoreal design renders of the branded lobby, green-toned bullpen and grey executive cabin. The palette mixes natural stone, wood veneer, geometric carpet and accent colour to balance a premium client-facing front with functional staff zones.",
    },
    gallery: [
      { src: "/assets/projects/akasa-noida/g01.jpg", alt: "Boardroom render with long black conference table, indoor trees behind glass, fluted drapery and geometric multicolour carpet.", span: "full" },
      { src: "/assets/projects/akasa-noida/g02.jpg", alt: "Executive cabin render in grey tones with sculptural desk, display shelving, planter and abstract artwork over timber flooring.", span: "half" },
      { src: "/assets/projects/akasa-noida/g03.jpg", alt: "Compact discussion room render with round table, tan leather chairs, wood-slat wall, wall-mounted screen and circular ceiling light.", span: "half" },
    ],
    featured: false,
    order: 11,
    seo: { title: "Akasa, Noida, Interior", description: "A corporate office fit-out in Noida for NBFC Pooja Fin Lease, pairing a double-height marble lobby with warm, material-rich boardrooms and bright open work" },
  },
  {
    slug: "arcelormittal-construction-office",
    name: "ArcelorMittal Construction Office",
    type: "Interior",
    client: "ArcelorMittal Construction",
    location: "India",
    city: "India",
    year: 2022,
    area: "",
    status: "design / render stage",
    scope: ["Commercial interior design and fit-out: reception", "Open-plan workstations", "Private cabins", "Breakout/lounge"],
    services: ["Interior", "Turnkey"],
    cover: "/assets/projects/arcelormittal-construction-office/cover.jpg",
    coverAlt: "Branded reception with timber feature wall, ArcelorMittal Construction signage, grey desk and yellow sofas.",
    narrative: {
      brief: "A high-rise corporate office fit-out for ArcelorMittal Construction, blending warm wood-and-orange branding with an industrial exposed-ceiling palette.",
      site: "Corporate office commission in India. design / render stage.",
      response: "Design renders for an ArcelorMittal Construction corporate office occupying an upper floor of a high-rise tower, with floor-to-ceiling city views throughout. The scheme pairs the brand's red/orange identity with timber paneling, exposed services ceilings, and grey carpet, spanning a branded reception, open workstation bays, private cabins, and an informal breakout lounge with a foosball table and ring pendant lights.",
    },
    gallery: [
      { src: "/assets/projects/arcelormittal-construction-office/g01.jpg", alt: "Open-plan workstation bays with branded screens, a central potted tree and a colourful pixel accent wall.", span: "full" },
      { src: "/assets/projects/arcelormittal-construction-office/g02.jpg", alt: "Breakout lounge with yellow modular seating, ring pendant lights, planters and floor-to-ceiling skyline glazing.", span: "half" },
      { src: "/assets/projects/arcelormittal-construction-office/g03.jpg", alt: "Private corner cabin in blue paneling with two-seat desk, framed warehouse artwork and panoramic city views.", span: "half" },
      { src: "/assets/projects/arcelormittal-construction-office/g04.jpg", alt: "Workstation floor viewed from a breakout zone with foosball table and glazed meeting rooms along the corridor.", span: "wide" },
    ],
    featured: false,
    order: 12,
    seo: { title: "ArcelorMittal Construction Office, Interior", description: "A high-rise corporate office fit-out for ArcelorMittal Construction, blending warm wood-and-orange branding with an industrial exposed-ceiling palette." },
  },
  {
    slug: "ca-office-andheri-west",
    name: "CA Office, Andheri West",
    type: "Interior",
    client: "Chartered Accountancy Firm (name withheld, \"Company Logo\" placeholder shown)",
    location: "Andheri West, Mumbai",
    city: "Mumbai",
    year: 2021,
    area: "",
    status: "design / 3D visualization",
    scope: ["Commercial interior design and fit-out of a chartered accountant office: reception/lobby", "Open-plan workstation bays", "And meeting/cabin areas."],
    services: ["Interior", "Turnkey"],
    cover: "/assets/projects/ca-office-andheri-west/cover.jpg",
    coverAlt: "Warm reception corridor with green glass conference room, slatted wood wall and framed abstract art.",
    narrative: {
      brief: "A compact Andheri West chartered-accountancy office where typographic feature walls and bold colour accents energise tight, efficient workstation bays.",
      site: "Professional services commission in Andheri West, Mumbai. design / 3D visualization.",
      response: "A set of 3D design renders for a chartered accountant's office in Andheri West, Mumbai. The scheme pairs warm wood-clad reception desks (branded with a placeholder \"Company Logo\") and tinted geometric-etched glass partitions with linear workstation bays accented in green, yellow and black. Playful \"Order of Operations\" and \"Success formula\" typographic murals reinforce the accountancy theme across the workspace.",
    },
    gallery: [
      { src: "/assets/projects/ca-office-andheri-west/g01.jpg", alt: "Bright workstation room framed by green glass, with a 'Success formula' typographic feature wall.", span: "full" },
      { src: "/assets/projects/ca-office-andheri-west/g02.jpg", alt: "Dramatic dark lobby with bright blue sofa, blue-yellow pendant and wood logo reception wall.", span: "half" },
      { src: "/assets/projects/ca-office-andheri-west/g03.jpg", alt: "Reception with white bench seating, geometric-etched glass and wood logo wall under a blue-yellow pendant.", span: "half" },
      { src: "/assets/projects/ca-office-andheri-west/g04.jpg", alt: "Workstation bay with yellow accent panel and bold 'Order of Operations' graphic banner.", span: "wide" },
      { src: "/assets/projects/ca-office-andheri-west/g05.jpg", alt: "Narrow workstation bay with green accent splashbacks and monochrome typographic mural wall.", span: "half" },
      { src: "/assets/projects/ca-office-andheri-west/g06.jpg", alt: "Black-and-white 'Order of Operations' banners over yellow-backed desks in a compact work bay.", span: "tall" },
      { src: "/assets/projects/ca-office-andheri-west/g07.jpg", alt: "Reception view with stone desk, etched-glass partitions and a small meeting table beyond.", span: "half" },
      { src: "/assets/projects/ca-office-andheri-west/g08.jpg", alt: "Workstation room seen through glass partition, with typographic banners and a cabin doorway beyond.", span: "wide" },
    ],
    featured: false,
    order: 13,
    seo: { title: "CA Office, Andheri West, Interior", description: "A compact Andheri West chartered-accountancy office where typographic feature walls and bold colour accents energise tight, efficient workstation bays." },
  },
  {
    slug: "ceat",
    name: "CEAT",
    type: "Architecture",
    client: "CEAT",
    location: "Ambernath, Mumbai",
    city: "Mumbai",
    year: 2020,
    area: "Ground + 1 structure",
    status: "Under construction",
    scope: ["Architecture"],
    services: ["Architecture"],
    cover: "/assets/projects/ceat/cover.jpg",
    coverAlt: "Front elevation render of the CEAT facility with the branded white volume meeting a glazed office block, framed by palms.",
    narrative: {
      brief: "A clean, low-slung industrial facility for CEAT pairing a solid branded volume with a glazed office block.",
      site: "Industrial commission in Ambernath, Mumbai. Under construction.",
      response: "Architectural design for a CEAT industrial facility in Ambernath, Mumbai, comprising a Ground + 1 structure housing machinery and offices. The renders show a minimal white volume carrying the CEAT branding, set against a fully glazed two-storey office wing with an external steel stair. The scheme is currently under construction.",
    },
    gallery: [
      { src: "/assets/projects/ceat/g01.jpg", alt: "Three-quarter view of the glazed two-storey office wing with external steel staircase and CEAT signage on the side wall.", span: "full" },
      { src: "/assets/projects/ceat/g02.jpg", alt: "Corner render showing the long white industrial volume with ribbon glazing wrapping to the branded glazed entrance.", span: "half" },
    ],
    featured: false,
    order: 14,
    seo: { title: "CEAT, Architecture", description: "A clean, low-slung industrial facility for CEAT pairing a solid branded volume with a glazed office block." },
  },
  {
    slug: "eatigo-office",
    name: "eatigo Office",
    type: "Interior",
    client: "eatigo",
    location: "India",
    city: "India",
    year: 2019,
    area: "",
    status: "Design / Concept (3D renders)",
    scope: ["Commercial interior design and workplace fit-out: open-plan workstations", "Meeting cabins", "Branded reception wall", "And breakout/cafeteria zones"],
    services: ["Interior", "Turnkey"],
    cover: "/assets/projects/eatigo-office/cover.jpg",
    coverAlt: "Sunlit eye-level view of workstations beside the red eatigo brick wall",
    narrative: {
      brief: "A bright, open-plan office fit-out for tech brand eatigo, anchored by a red-on-white-brick logo wall and rows of warm-wood workstations.",
      site: "IT commission. Design / Concept (3D renders).",
      response: "A set of 3D visualisations for the eatigo workplace interior, showing an open-plan floor of bench-style wooden workstations with orange acoustic screens, glass-partitioned meeting cabins, and a casual breakout area with bean bags, bar stools and a whiteboard. The scheme centres on a white exposed-brick feature wall carrying the eatigo logo in red, paired with blue/orange accent panels and warm timber flooring. All assets are concept renders, including several aerial cutaway floor plans of the full layout.",
    },
    gallery: [
      { src: "/assets/projects/eatigo-office/g01.jpg", alt: "Aerial perspective focused on the eatigo brand wall and desk clusters", span: "full" },
      { src: "/assets/projects/eatigo-office/g02.jpg", alt: "Frontal eye-level view of workstations against the eatigo logo wall", span: "half" },
      { src: "/assets/projects/eatigo-office/g03.jpg", alt: "Interior view of bench workstations with laptops and mesh task chairs", span: "half" },
      { src: "/assets/projects/eatigo-office/g04.jpg", alt: "Breakout zone with bar stools, bean bags, whiteboard and high tables", span: "wide" },
      { src: "/assets/projects/eatigo-office/g05.jpg", alt: "Top-down cutaway render of the workstation floor and meeting cabins", span: "half" },
      { src: "/assets/projects/eatigo-office/g06.jpg", alt: "Aerial cutaway showing bench desks, breakout seating and cafeteria zone", span: "tall" },
      { src: "/assets/projects/eatigo-office/g07.jpg", alt: "Angled aerial cutaway of the full office layout with workstation rows", span: "half" },
      { src: "/assets/projects/eatigo-office/g08.jpg", alt: "Perspective cutaway of open-plan desks and a blue-walled meeting room", span: "wide" },
      { src: "/assets/projects/eatigo-office/g09.jpg", alt: "Angled aerial render highlighting workstation clusters and cabins", span: "full" },
      { src: "/assets/projects/eatigo-office/g10.jpg", alt: "Distant top-down render of the floor plan, sparsely furnished", span: "full" },
    ],
    featured: false,
    order: 15,
    seo: { title: "eatigo Office, Interior", description: "A bright, open-plan office fit-out for tech brand eatigo, anchored by a red-on-white-brick logo wall and rows of warm-wood workstations." },
  },
  {
    slug: "evos-sales-office",
    name: "Evos Sales Office",
    type: "Interior",
    client: "Evos",
    location: "India",
    city: "India",
    year: 2018,
    area: "",
    status: "Design / Visualization (3D renders)",
    scope: ["Interior design for a real-estate sales / experience office", "Including reception", "Waiting lounge", "Model-display area", "Cabins"],
    services: ["Interior"],
    cover: "/assets/projects/evos-sales-office/cover.jpg",
    coverAlt: "Curved marble reception desk framed by fluted stone wall panels and the backlit evos logo, with a circular marble floor inlay.",
    narrative: {
      brief: "A sculptural, fluted-stone sales office for the Evos brand, organised around a sweeping reception and a central architectural model display.",
      site: "Real estate commission. Design / Visualization (3D renders).",
      response: "A real-estate sales and experience office designed for the Evos brand, presented as a set of polished 3D renders plus a fully annotated floor plan. The space is defined by undulating, ribbed stone-textured wall panels, marble flooring with inlaid circular patterns, and a wood-slat ceiling, with sculptural copper-line pendant fixtures as a recurring motif. Spaces include a curved reception desk under the backlit \"evos\" logo, a model-display table with a bonsai water feature, a lounge with green accent chairs opening to a garden, and a glazed meeting room.",
    },
    gallery: [
      { src: "/assets/projects/evos-sales-office/g01.jpg", alt: "Open lounge with green accent chairs and curved sofas around the model-display feature, sculptural pendants overhead and garden views beyond.", span: "full" },
      { src: "/assets/projects/evos-sales-office/g02.jpg", alt: "Glazed meeting room with timber table and green chairs, viewed between undulating fluted-stone columns over marble flooring.", span: "half" },
      { src: "/assets/projects/evos-sales-office/g03.jpg", alt: "Annotated furniture floor plan showing reception, model stable, waiting lounge, cabins, meeting and conference rooms, plus a residential wing.", span: "half" },
    ],
    featured: false,
    order: 16,
    seo: { title: "Evos Sales Office, Interior", description: "A sculptural, fluted-stone sales office for the Evos brand, organised around a sweeping reception and a central architectural model display." },
  },
  {
    slug: "fedbank-financial-services-kanakia-wallstreet",
    name: "Fedbank Financial Services, Kanakia Wallstreet",
    type: "Interior",
    client: "Fedbank Financial Services Limited (Federal Bank group)",
    location: "Kanakia Wallstreet, Andheri, Mumbai",
    city: "Mumbai",
    year: 2017,
    area: "",
    status: "Design / visualization stage",
    scope: ["Corporate office interior fit-out", "Reception", "Cabins", "Meeting rooms and gallery passage"],
    services: ["Interior", "Turnkey"],
    cover: "/assets/projects/fedbank-financial-services-kanakia-wallstreet/cover.jpg",
    coverAlt: "Reception with a lush green living wall and backlit FEDBANK signage above a sculpted white desk.",
    narrative: {
      brief: "A polished corporate banking office for Fedbank at Kanakia Wallstreet, blending a living-wall reception with refined dark-and-timber meeting suites.",
      site: "Banking commission in Kanakia Wallstreet, Andheri, Mumbai. Design / visualization stage.",
      response: "A set of 3D visualizations for Fedbank Financial Services Limited's office interiors at Kanakia Wallstreet, Mumbai. The design pairs a green living-wall reception carrying backlit FEDBANK branding with a series of neutral and timber-clad meeting rooms, a private cabin, and a dramatic black-panelled gallery passage lined with framed heritage Bombay artwork. The palette leans on warm wood, charcoal, soft greys and accents of teal and ochre for a calm, premium banking environment.",
    },
    gallery: [
      { src: "/assets/projects/fedbank-financial-services-kanakia-wallstreet/g01.jpg", alt: "Dramatic black-panelled gallery passage lined with framed heritage Bombay prints and a glossy stone floor.", span: "full" },
      { src: "/assets/projects/fedbank-financial-services-kanakia-wallstreet/g02.jpg", alt: "Manager's cabin with timber feature wall, L-shaped desk and a teal tub-chair discussion nook.", span: "half" },
      { src: "/assets/projects/fedbank-financial-services-kanakia-wallstreet/g03.jpg", alt: "Meeting room with warm timber-top table, fabric-panel walls and projection screen.", span: "half" },
      { src: "/assets/projects/fedbank-financial-services-kanakia-wallstreet/g04.jpg", alt: "Boardroom with dark stone table, neutral panelled walls and pull-down projection screen.", span: "wide" },
      { src: "/assets/projects/fedbank-financial-services-kanakia-wallstreet/g05.jpg", alt: "Conference room with playful coloured acoustic-tile feature wall and white meeting table.", span: "half" },
    ],
    featured: false,
    order: 17,
    seo: { title: "Fedbank Financial Services, Kanakia Wallstreet, Interior", description: "A polished corporate banking office for Fedbank at Kanakia Wallstreet, blending a living-wall reception with refined dark-and-timber meeting suites." },
  },
  {
    slug: "fox-mandal-the-capital",
    name: "Fox Mandal, The Capital",
    type: "Interior",
    client: "Fox Mandal Solicitors & Advocates",
    location: "The Capital",
    city: "The Capital",
    year: 2025,
    area: "",
    status: "Design / visualization (3D renders)",
    scope: ["Commercial office interior fit-out", "Reception", "Open-plan workstations", "Conference/meeting rooms and washrooms"],
    services: ["Interior", "Turnkey"],
    cover: "/assets/projects/fox-mandal-the-capital/cover.jpg",
    coverAlt: "Reception with grey marble feature wall, Fox Mandal Solicitors & Advocates signage and FM monogram.",
    narrative: {
      brief: "A restrained, marble-and-walnut office fit-out for law firm Fox Mandal Solicitors & Advocates at The Capital.",
      site: "Legal commission in The Capital. Design / visualization (3D renders).",
      response: "Interior design visualization for the Fox Mandal Solicitors & Advocates office at The Capital, presented as a set of 3D renders. The scheme pairs a grey marble reception feature wall carrying the firm's \"FM\" monogram with walnut-veneer overhead storage, white worktop desks and grey carpet tiles across open-plan workstation bays. Supporting spaces include glazed conference and meeting rooms and travertine-and-marble washrooms.",
    },
    gallery: [
      { src: "/assets/projects/fox-mandal-the-capital/g01.jpg", alt: "Reception desk and FM marble wall with accreditation frames and warm cove lighting.", span: "full" },
      { src: "/assets/projects/fox-mandal-the-capital/g02.jpg", alt: "Long axial view down a row of workstations framed by walnut storage and grey carpet tiles.", span: "half" },
      { src: "/assets/projects/fox-mandal-the-capital/g03.jpg", alt: "Boardroom with long white table, grey upholstered chairs, cove lighting and wall display.", span: "half" },
      { src: "/assets/projects/fox-mandal-the-capital/g04.jpg", alt: "Open-plan workstation bay with white desks, mesh task chairs and walnut overhead storage.", span: "wide" },
      { src: "/assets/projects/fox-mandal-the-capital/g05.jpg", alt: "Travertine-tiled washroom with marble vanity, wall-hung urinal and dark stone floor.", span: "half" },
      { src: "/assets/projects/fox-mandal-the-capital/g06.jpg", alt: "Washroom with glass shower, wall-hung WC, vessel basin and travertine walls.", span: "tall" },
    ],
    featured: false,
    order: 18,
    seo: { title: "Fox Mandal, The Capital, Interior", description: "A restrained, marble-and-walnut office fit-out for law firm Fox Mandal Solicitors & Advocates at The Capital." },
  },
  {
    slug: "indiana-business",
    name: "Indiana Business",
    type: "Interior",
    client: "Indiana Business",
    location: "India",
    city: "India",
    year: 2024,
    area: "",
    status: "Concept / design visualization",
    scope: ["Commercial office interior design"],
    services: ["Interior"],
    cover: "/assets/projects/indiana-business/cover.jpg",
    coverAlt: "Long open-plan workstation bay with rows of iMac desks, mesh task chairs, and suspended green light troughs beneath an exposed services ceiling.",
    narrative: {
      brief: "A bright, green-accented open-plan office where exposed-services ceilings meet rows of long-bench workstations.",
      site: "IT commission. Concept / design visualization.",
      response: "Two interior renders of the Indiana Business open office, showing a long, daylit floor plate lined with linear desking and ergonomic task chairs under an exposed concrete ceiling with painted services. The scheme runs a crisp green-grey-white palette, with green portal frames, suspended green light troughs, and a graphic wall mural that lends the corporate workspace a clean, energetic identity.",
    },
    gallery: [
      { src: "/assets/projects/indiana-business/g01.jpg", alt: "Circulation spine alongside the open office, featuring a white-and-grey storage credenza, a green figural wall mural, and green portal-framed openings.", span: "full" },
    ],
    featured: false,
    order: 19,
    seo: { title: "Indiana Business, Interior", description: "A bright, green-accented open-plan office where exposed-services ceilings meet rows of long-bench workstations." },
  },
  {
    slug: "jagasara-duplex",
    name: "Jagasara Duplex",
    type: "Architecture",
    client: "Jagasara Duplex Row Houses",
    location: "Odisha, India",
    city: "India",
    year: 2023,
    area: "5,000 sq.ft.",
    status: "Ongoing",
    scope: ["Architecture", "Interiors and landscape", "Design and execution"],
    services: ["Architecture", "Interior"],
    cover: "/assets/projects/jagasara-duplex/cover.jpg",
    coverAlt: "Street-level render of the full row of duplex houses showing the repeating louvered facade, planted balconies and boundary walls with a parked car.",
    narrative: {
      brief: "A row of contemporary duplex houses in Odisha defined by vertical louvered screens, cantilevered volumes and terraced greenery.",
      site: "Residential commission in Odisha, India. Ongoing.",
      response: "Jagasara is an ongoing residential development of duplex row houses in Odisha, with Madane handling architecture, interiors and landscape as a single design-and-execution mandate over roughly 5,000 sq.ft. The rendered design language pairs warm taupe and beige massing with tall vertical fins and slatted screens, planted balconies, and a stacked play of solid and recessed volumes. Floor plans reveal a ground-level portico, drawing and kitchen, first-floor bedrooms with a puja room, and a terrace level featuring a jacuzzi, viewing deck and seating corner.",
    },
    gallery: [
      { src: "/assets/projects/jagasara-duplex/g01.jpg", alt: "Perspective render down the row of duplexes with deep balcony planters and stepped louvered bays receding along the street.", span: "full" },
      { src: "/assets/projects/jagasara-duplex/g02.jpg", alt: "Corner three-quarter render of an end unit emphasising the massing of solid taupe blocks against slatted screens and cascading greenery.", span: "half" },
      { src: "/assets/projects/jagasara-duplex/g03.jpg", alt: "Frontal render of a single duplex unit framed by trees, highlighting the vertical fin screens, cantilevered top volume and green balcony planters.", span: "half" },
      { src: "/assets/projects/jagasara-duplex/g04.jpg", alt: "Massing development diagram showing the progression from solid block to carved voids, inserted volumes and final louvered facade.", span: "wide" },
    ],
    featured: false,
    order: 20,
    seo: { title: "Jagasara Duplex, Architecture", description: "A row of contemporary duplex houses in Odisha defined by vertical louvered screens, cantilevered volumes and terraced greenery." },
  },
  {
    slug: "omkar-techinvention",
    name: "Omkar Techinvention",
    type: "Interior",
    client: "Omkar Techinvention",
    location: "India",
    city: "India",
    year: 2022,
    area: "",
    status: "Design / Render",
    scope: ["Commercial office interior design"],
    services: ["Interior"],
    cover: "/assets/projects/omkar-techinvention/cover.jpg",
    coverAlt: "Pantry and coffee-bar lounge with green-accented stools, suspended pendant planters and a panoramic night-time city view.",
    narrative: {
      brief: "A high-rise corporate office interior pairing a motivational glass-walled meeting room with a vibrant city-view coffee bar.",
      site: "IT commission. Design / Render.",
      response: "Design renders for the Omkar Techinvention office, a contemporary corporate workplace set high above a city skyline. The scheme features a glass-partitioned meeting room with a typographic \"Creative Teamwork Innovate\" feature wall, and a bright pantry-cafe zone with green-accented furniture, pendant lighting and panoramic glazing. The palette mixes monochrome carpeting and ceilings with lime-green highlights and natural-wood seating.",
    },
    gallery: [
      { src: "/assets/projects/omkar-techinvention/g01.jpg", alt: "Glass-walled meeting room with a typographic 'Creative Teamwork Innovate' feature wall and black executive chairs.", span: "full" },
    ],
    featured: false,
    order: 21,
    seo: { title: "Omkar Techinvention, Interior", description: "A high-rise corporate office interior pairing a motivational glass-walled meeting room with a vibrant city-view coffee bar." },
  },
  {
    slug: "reynaers-aluminium-office-5th-floor-oberoi-garden",
    name: "Reynaers Aluminium Office, 5th Floor, Oberoi Garden",
    type: "Interior",
    client: "Reynaers Aluminium",
    location: "Oberoi Garden, Mumbai",
    city: "Mumbai",
    year: 2021,
    area: "",
    status: "Design visualization (3D renders)",
    scope: ["Commercial interior fit-out and design", "Reception", "Open-plan workstations", "Breakout/collaboration zones", "Glazed meeting rooms"],
    services: ["Interior", "Turnkey"],
    cover: "/assets/projects/reynaers-aluminium-office-5th-floor-oberoi-garden/cover.jpg",
    coverAlt: "Reception lounge with curved white desk and the branded REYNAERS aluminium frosted-glass screen, video wall and waiting seating.",
    narrative: {
      brief: "A bright, glass-and-aluminium corporate office for Reynaers on the 5th floor at Oberoi Garden, branded around the company's signature blue.",
      site: "Corporate office commission in Oberoi Garden, Mumbai. Design visualization (3D renders).",
      response: "A full commercial interior design for Reynaers Aluminium occupying the 5th floor of Oberoi Garden. The scheme pairs a high-gloss white floor and grey-brick feature walls with the brand's signature blue accents, most visibly in the frosted-glass reception screen carrying the REYNAERS aluminium logo, the blue-framed glazing display, and graphic \"MEETING 01/02\" glass partitions. Spaces shown include the reception lounge, open-plan workstations, padded breakout pods, and enclosed boardrooms, all presented as polished 3D visualizations.",
    },
    gallery: [
      { src: "/assets/projects/reynaers-aluminium-office-5th-floor-oberoi-garden/g01.jpg", alt: "Wide reception view linking the branded desk, glass meeting room and waiting lounge in one bright open volume.", span: "full" },
      { src: "/assets/projects/reynaers-aluminium-office-5th-floor-oberoi-garden/g02.jpg", alt: "Glazed display vitrines framed in brand-blue showcasing aluminium window systems along a bright corridor.", span: "half" },
      { src: "/assets/projects/reynaers-aluminium-office-5th-floor-oberoi-garden/g03.jpg", alt: "Open-plan workstations with blue-accented desks, timber-slat wall and linear ceiling lighting.", span: "half" },
      { src: "/assets/projects/reynaers-aluminium-office-5th-floor-oberoi-garden/g04.jpg", alt: "Breakout/collaboration zone with upholstered high-back pods and pendant drum lights beside the open workspace.", span: "wide" },
      { src: "/assets/projects/reynaers-aluminium-office-5th-floor-oberoi-garden/g05.jpg", alt: "Glazed boardrooms with bold 'MEETING 01 / 02' graphic film on the partition glass.", span: "half" },
    ],
    featured: false,
    order: 22,
    seo: { title: "Reynaers Aluminium Office, 5th Floor, Oberoi Garden, Interior", description: "A bright, glass-and-aluminium corporate office for Reynaers on the 5th floor at Oberoi Garden, branded around the company's signature blue." },
  },
  {
    slug: "reynaers-office",
    name: "Reynaers Office",
    type: "Interior",
    client: "Reynaers Aluminium",
    location: "India",
    city: "India",
    year: 2020,
    area: "",
    status: "Design / visualization stage",
    scope: ["Commercial interior design and fit-out of a corporate office: reception", "Open-plan workstations", "Meeting rooms", "Breakout/lounge zones"],
    services: ["Interior", "Turnkey"],
    cover: "/assets/projects/reynaers-office/cover.jpg",
    coverAlt: "Reception with backlit desk, concrete pendant, project video-wall and the etched Reynaers R logo on the glass partition.",
    narrative: {
      brief: "A sleek corporate office fit-out for aluminium-systems brand Reynaers, blending a backlit reception, glass-walled meeting rooms and a green-accented open-plan floor on a curved \"boomerang\" plate.",
      site: "Corporate office commission. Design / visualization stage.",
      response: "A set of polished 3D visualizations for a Reynaers corporate office, identifiable by the brand \"R\" mark etched on the reception glass partition. The scheme pairs a crisp white-and-grey palette with warm timber accents, signature red linear-light reflections across exposed ceilings, and planted timber benches that bring greenery into the open-plan workstation areas. Key zones include a backlit reception with video-wall, multiple glass-enclosed meeting rooms with light-timber boardroom tables, and informal breakout pods. The bird's-eye render reveals the building's distinctive curved, boomerang-shaped floor plate.",
    },
    gallery: [
      { src: "/assets/projects/reynaers-office/g01.jpg", alt: "Open-plan floor framed by black folding glass partitions, leading to workstations and a meeting room with greenery.", span: "full" },
      { src: "/assets/projects/reynaers-office/g02.jpg", alt: "Boardroom with timber conference table, white leather chairs, recessed cove lighting and a blue back-painted glass feature.", span: "half" },
      { src: "/assets/projects/reynaers-office/g03.jpg", alt: "Open-plan office with planted timber bench, white desks and warm wood storage wall against floor-to-ceiling glazing.", span: "half" },
      { src: "/assets/projects/reynaers-office/g04.jpg", alt: "Cutaway bird's-eye render of the full office plan on its curved boomerang-shaped floor plate, showing reception, workstations and meeting zones.", span: "wide" },
      { src: "/assets/projects/reynaers-office/g05.jpg", alt: "Glass-walled breakout pod with timber-and-orange bench seating amid dark-framed glazed partitions and red ceiling accents.", span: "half" },
      { src: "/assets/projects/reynaers-office/g06.jpg", alt: "Open-plan workstation bays with white benching desks, iMacs and potted trees under red-accented linear lighting.", span: "tall" },
      { src: "/assets/projects/reynaers-office/g07.jpg", alt: "Glass-enclosed boardroom seen through partitions, with light-timber table, white Eames-style chairs and wall display.", span: "half" },
      { src: "/assets/projects/reynaers-office/g08.jpg", alt: "Bright reception lounge with curved white desk, lounge seating and a glazed meeting room beyond; Reynaers logo on glass.", span: "wide" },
      { src: "/assets/projects/reynaers-office/g09.jpg", alt: "Workstation zone with planted timber benches, white desks and warm wood accent wall under red linear lighting.", span: "full" },
    ],
    featured: false,
    order: 23,
    seo: { title: "Reynaers Office, Interior", description: "A sleek corporate office fit-out for aluminium-systems brand Reynaers, blending a backlit reception, glass-walled meeting rooms and a green-accented open-p" },
  },
  {
    slug: "semac-office-l-and-t-seawoods",
    name: "SEMAC Office, L&T Seawoods",
    type: "Interior",
    client: "SEMAC (at L&T Seawoods)",
    location: "L&T Seawoods Grand Central, Navi Mumbai",
    city: "Navi Mumbai",
    year: 2019,
    area: "",
    status: "design / render stage",
    scope: ["Commercial interior fit-out", "Reception", "Open-plan workstations", "Meeting room", "Breakout and biophilic zones"],
    services: ["Interior", "Turnkey"],
    cover: "/assets/projects/semac-office-l-and-t-seawoods/cover.jpg",
    coverAlt: "SEMAC reception with a sculptural white curved desk, arched wood portals, sacred statuary and green lounge seating over terrazzo flooring.",
    narrative: {
      brief: "A warm, biophilic corporate office for SEMAC at L&T Seawoods, defined by sculptural arched wood portals, Indian mythological murals and lush greenery.",
      site: "Engineering consultancy / corporate office commission in L&T Seawoods Grand Central, Navi Mumbai. design / render stage.",
      response: "A set of 3D design renders for SEMAC's office interior at L&T Seawoods, Navi Mumbai. The scheme pairs a curved sculptural reception desk (branded SEMAC) with arched wood-veneer portals, terrazzo-patterned flooring, abundant indoor planting, and Indian mythological wall art and textual murals. Open-plan workstation clusters, a glass-enclosed conference room, and green-upholstered lounge seating round out a warm, culturally-rooted corporate environment.",
    },
    gallery: [
      { src: "/assets/projects/semac-office-l-and-t-seawoods/g01.jpg", alt: "Wide open-office view with bench desking, illuminated arch niche, biophilic greenery and a patterned terrazzo runner.", span: "full" },
      { src: "/assets/projects/semac-office-l-and-t-seawoods/g02.jpg", alt: "Workstation cluster with a dramatic mythological archer mural, arched wood passage and lush indoor trees.", span: "half" },
      { src: "/assets/projects/semac-office-l-and-t-seawoods/g03.jpg", alt: "View from reception into the open-plan workstation bay, framed by arched wood portals, planting and green lounge chairs.", span: "half" },
      { src: "/assets/projects/semac-office-l-and-t-seawoods/g04.jpg", alt: "Glass-walled conference room with a long white table, leather chairs, wall display and stained-glass-style art panels.", span: "wide" },
      { src: "/assets/projects/semac-office-l-and-t-seawoods/g05.jpg", alt: "Workstation desks beside a botanical chinoiserie feature wall and textured stone surface, with arched wood portal beyond.", span: "half" },
    ],
    featured: false,
    order: 24,
    seo: { title: "SEMAC Office, L&T Seawoods, Interior", description: "A warm, biophilic corporate office for SEMAC at L&T Seawoods, defined by sculptural arched wood portals, Indian mythological murals and lush greenery." },
  },
  {
    slug: "sus-residential-development",
    name: "Sus Residential Development",
    type: "Architecture",
    client: "Sus, Pune",
    location: "Sus, Pune, India",
    city: "India",
    year: 2018,
    area: "G+13 residential towers",
    status: "Design stage",
    scope: ["Architecture and landscape design"],
    services: ["Architecture"],
    cover: "/assets/projects/sus-residential-development/cover.jpg",
    coverAlt: "Aerial view of the U-shaped tower cluster framing a landscaped podium courtyard with pool and palm rows.",
    narrative: {
      brief: "A G+13 residential township in Sus, Pune, wrapping landscaped courtyards and a pool deck within a crisp white modernist tower cluster.",
      site: "Residential commission in Sus, Pune, India. Design stage.",
      response: "A large-scale residential development in Sus, Pune, comprising multiple G+13 towers with clean white facades and a regular grid of recessed balconies. The renders showcase a generous central courtyard with palm-lined walkways, circular tree planters with seating, and a swimming pool atop a podium. The project is at the design stage, with architecture and landscape both within the studio's scope.",
    },
    gallery: [
      { src: "/assets/projects/sus-residential-development/g01.jpg", alt: "Street-level elevation of the white G+13 towers with rhythmic balconies above a landscaped green frontage.", span: "full" },
      { src: "/assets/projects/sus-residential-development/g02.jpg", alt: "Tower base and amphitheatre-style landscaped deck lined with date palms and a pool edge.", span: "half" },
      { src: "/assets/projects/sus-residential-development/g03.jpg", alt: "Ground-level courtyard render with circular tree planters and seating, residents relaxing beneath shade trees.", span: "half" },
    ],
    featured: false,
    order: 25,
    seo: { title: "Sus Residential Development, Architecture", description: "A G+13 residential township in Sus, Pune, wrapping landscaped courtyards and a pool deck within a crisp white modernist tower cluster." },
  },
  {
    slug: "swastik-group-residential-towers",
    name: "Swastik Group Residential Towers",
    type: "Architecture",
    client: "Swastik Group",
    location: "Mumbai, Maharashtra (Mulund / Pantnagar, along the Eastern Express Highway)",
    city: "Mumbai",
    year: 2017,
    area: "Swastik Platinum terrace carpet area approx. 4,130 sq.ft (per terrace plan); full project areas not specified",
    status: "design / render stage (proposed)",
    scope: ["Architecture and amenity / terrace landscape design across multiple residential towers (Swastik Platinum", "Pearl", "Divine and Pantnagar)"],
    services: ["Architecture"],
    cover: "/assets/projects/swastik-group-residential-towers/cover.jpg",
    coverAlt: "Hero daytime render of the full Swastik Platinum tower with a textured grille facade and planted podium.",
    narrative: {
      brief: "A family of high-rise residential towers for the Swastik Group, lifting landscaped play decks, infinity pools and sky lounges onto the Mumbai skyline.",
      site: "Residential commission in Mumbai, Maharashtra (Mulund / Pantnagar, along the Eastern Express Highway). design / render stage (proposed).",
      response: "This folder collects architecture and amenity-deck design work for several Swastik Group residential high-rises in Mumbai - Swastik Platinum, Pearl, Divine (Mulund) and Pantnagar - sited along the Eastern Express Highway. The renders show tall, slender towers with grilled facades and a planted entrance canopy, paired with elevated terrace amenities including an infinity pool, a colourful children's play deck, a turfed cricket / jogging track and shaded outdoor dining lounges. A large supporting set of colour terrace and amenity-floor plans documents the layout of these rooftop recreation decks (one noted at ~4,130 sq.ft).",
    },
    gallery: [
      { src: "/assets/projects/swastik-group-residential-towers/g01.jpg", alt: "Elevated infinity pool deck with timber flooring, loungers and open skyline views at dusk.", span: "full" },
      { src: "/assets/projects/swastik-group-residential-towers/g02.jpg", alt: "Street-level render of the Platinum tower base with a planted entrance canopy and concentric-motif entry portal.", span: "half" },
      { src: "/assets/projects/swastik-group-residential-towers/g03.jpg", alt: "Detailed Pantnagar terrace plan with jogging track, slides, trampoline, swings and elders' night-gazing seating.", span: "half" },
      { src: "/assets/projects/swastik-group-residential-towers/g04.jpg", alt: "Apartment balcony with timber ceiling, vertical garden and lounge seating overlooking the highway and open landscape.", span: "wide" },
      { src: "/assets/projects/swastik-group-residential-towers/g05.jpg", alt: "Dusk render of the tower's lit balconies and a screened sky-deck crown above a green setting.", span: "half" },
      { src: "/assets/projects/swastik-group-residential-towers/g06.jpg", alt: "Rooftop children's play deck with pastel disc canopies, sculpted mounds and a sunset skyline backdrop.", span: "tall" },
      { src: "/assets/projects/swastik-group-residential-towers/g07.jpg", alt: "Aerial view of the tower complex set within landscaped grounds and surrounding greenery.", span: "half" },
      { src: "/assets/projects/swastik-group-residential-towers/g08.jpg", alt: "Indoor multipurpose sports corridor with turf cricket pitch, net enclosure and slatted wall detailing.", span: "wide" },
      { src: "/assets/projects/swastik-group-residential-towers/g09.jpg", alt: "Landscaped terrace dining lounge with sculptural light columns, mature trees and curved walking paths.", span: "full" },
    ],
    featured: false,
    order: 26,
    seo: { title: "Swastik Group Residential Towers, Architecture", description: "A family of high-rise residential towers for the Swastik Group, lifting landscaped play decks, infinity pools and sky lounges onto the Mumbai skyline." },
  },
  {
    slug: "tata-elxsi",
    name: "Tata Elxsi",
    type: "Architecture",
    client: "Tata Elxsi",
    location: "Bangalore, India",
    city: "India",
    year: 2025,
    area: "18 floors",
    status: "Design stage",
    scope: ["Architectural planning and detailing"],
    services: ["Architecture"],
    cover: "/assets/projects/tata-elxsi/cover.jpg",
    coverAlt: "Frontal street-level render of the office tower, glazed fin facade cantilevered over a palm-lined drop-off and entrance.",
    narrative: {
      brief: "An 18-storey commercial office tower in Bangalore, capped by a dramatic cantilevered glass-and-fin upper volume floating over a screened podium.",
      site: "IT / commercial development commission in Bangalore, India. Design stage.",
      response: "A design-stage commercial development for Tata Elxsi in Bangalore comprising an 18-floor office building. The architecture pairs a fritted vertical-fin curtain-wall upper block, cantilevered over a louvered podium with a landscaped forecourt and palm-lined drop-off. Supporting diagrams work through site massing, circulation, green-space planning, and a sectional study showing two basement levels and a refuge floor.",
    },
    gallery: [
      { src: "/assets/projects/tata-elxsi/g01.jpg", alt: "Side elevation render emphasizing the floating upper glass volume over the ribbed podium and screened ground floor.", span: "full" },
      { src: "/assets/projects/tata-elxsi/g02.jpg", alt: "Three-quarter dusk render of the cantilevered tower with vertical fins, set among low neighbouring blocks and landscaping.", span: "half" },
      { src: "/assets/projects/tata-elxsi/g03.jpg", alt: "Building section through the tower showing two basement levels and a labelled refuge floor against the streetscape.", span: "half" },
      { src: "/assets/projects/tata-elxsi/g04.jpg", alt: "Site programming diagram with icons for greenery, pedestrian access and office use over the plot footprint.", span: "wide" },
      { src: "/assets/projects/tata-elxsi/g05.jpg", alt: "Massing build-up diagram showing the twin floored volumes rising with a green roof terrace and view orientation.", span: "half" },
      { src: "/assets/projects/tata-elxsi/g06.jpg", alt: "Early massing study of two solid blocks on the site with the landscaped strip and access road.", span: "tall" },
      { src: "/assets/projects/tata-elxsi/g07.jpg", alt: "Vehicular circulation diagram tracing the entry/exit loop around the building footprint.", span: "half" },
    ],
    featured: false,
    order: 27,
    seo: { title: "Tata Elxsi, Architecture", description: "An 18-storey commercial office tower in Bangalore, capped by a dramatic cantilevered glass-and-fin upper volume floating over a screened podium." },
  },
  {
    slug: "ve-commercial-vehicles-volvo-eicher-office",
    name: "VE Commercial Vehicles (Volvo Eicher) Office",
    type: "Interior",
    client: "VE Commercial Vehicles (VECV)",
    location: "India",
    city: "India",
    year: 2024,
    area: "",
    status: "Design visualization (3D renders)",
    scope: ["Commercial interior fit-out", "Reception", "Open-plan workstations", "Cabins and meeting rooms"],
    services: ["Interior", "Turnkey"],
    cover: "/assets/projects/ve-commercial-vehicles-volvo-eicher-office/cover.jpg",
    coverAlt: "Open-plan workfloor with linear pendant lighting, exposed services ceiling, green living wall and panoramic city-view glazing.",
    narrative: {
      brief: "A crisp, brand-led corporate office for VE Commercial Vehicles, balancing an open high-rise workfloor with a clean white reception.",
      site: "Automotive commission. Design visualization (3D renders).",
      response: "A commercial-interior design for VE Commercial Vehicles (the Volvo Eicher joint venture), presented as 3D renders. The scheme pairs a bright, minimal white reception and waiting lounge, accented with red-and-blue brand-coloured artwork, with a large open-plan workfloor featuring linear pendant lighting, an exposed services ceiling, a green living wall and panoramic city-view glazing. Glass-partitioned meeting rooms and cabins extend the clean, contemporary corporate language.",
    },
    gallery: [
      { src: "/assets/projects/ve-commercial-vehicles-volvo-eicher-office/g01.jpg", alt: "Minimal white reception with VE Commercial Vehicles signage, grey desk, cassette AC ceiling and brand-coloured wall art.", span: "full" },
      { src: "/assets/projects/ve-commercial-vehicles-volvo-eicher-office/g02.jpg", alt: "Waiting lounge with grey sofa, marble coffee table and bold red-blue brand artwork, beside glass-partitioned meeting rooms.", span: "half" },
    ],
    featured: false,
    order: 28,
    seo: { title: "VE Commercial Vehicles (Volvo Eicher) Office, Interior", description: "A crisp, brand-led corporate office for VE Commercial Vehicles, balancing an open high-rise workfloor with a clean white reception." },
  },
  {
    slug: "vinay-savargi-c-a-office-andheri",
    name: "Vinay Savargi C.A. Office, Andheri",
    type: "Interior",
    client: "Vinay Savargi (Chartered Accountant)",
    location: "Andheri, Mumbai",
    city: "Mumbai",
    year: 2023,
    area: "",
    status: "design / visualization stage",
    scope: ["Commercial interior design and space planning for a chartered accountant's office"],
    services: ["Interior"],
    cover: "/assets/projects/vinay-savargi-c-a-office-andheri/cover.jpg",
    coverAlt: "Cutaway render foregrounding the conference cabin and workstation bay, with the wooden circulation corridor sweeping across the upper left.",
    narrative: {
      brief: "A compact chartered accountant's office in Andheri, space-planned into private cabins, open workstations and meeting zones through clean 3D cutaway renders.",
      site: "Professional services (chartered accountant office) commission in Andheri, Mumbai. design / visualization stage.",
      response: "Interior design for Vinay Savargi's chartered accountant practice in Andheri, presented entirely as 3D cutaway dollhouse renders showing the full floor layout from four angles. The plan organizes the space into glass-partitioned private cabins, a row of open workstations, a round-table meeting/conference area, and a long wood-floored circulation/reception corridor. The scheme uses a neutral grey-and-white palette with dark glass partitions and warm wooden flooring to define the public spine.",
    },
    gallery: [
      { src: "/assets/projects/vinay-savargi-c-a-office-andheri/g01.jpg", alt: "3D cutaway showing the meeting cabin with display screen, clustered cabins and the long wood-floored reception passage.", span: "full" },
      { src: "/assets/projects/vinay-savargi-c-a-office-andheri/g02.jpg", alt: "Top-down 3D cutaway from an alternate angle, highlighting the cafeteria/breakout seating, cabins and the wood-floored reception spine.", span: "half" },
      { src: "/assets/projects/vinay-savargi-c-a-office-andheri/g03.jpg", alt: "3D cutaway render of the office showing open workstations, glass cabins and the round meeting table, with the wooden-floored corridor along the right.", span: "half" },
    ],
    featured: false,
    order: 29,
    seo: { title: "Vinay Savargi C.A. Office, Andheri, Interior", description: "A compact chartered accountant's office in Andheri, space-planned into private cabins, open workstations and meeting zones through clean 3D cutaway renders" },
  },
  {
    slug: "wonese-world-networking-services-office",
    name: "Wonese, World Networking Services Office",
    type: "Interior",
    client: "Wonese (World Networking Services)",
    location: "India",
    city: "India",
    year: 2022,
    area: "",
    status: "Design visualisation / render",
    scope: ["Commercial office interior design and fit-out"],
    services: ["Interior", "Turnkey"],
    cover: "/assets/projects/wonese-world-networking-services-office/cover.jpg",
    coverAlt: "Reception with bold red WONESE branding on a dark wood feature wall above a crisp white desk, framed by a glazed meeting cabin.",
    narrative: {
      brief: "An industrial-modern office fit-out for an IT networking firm, blending exposed red services overhead with warm wood and a bold red-on-black brand identity.",
      site: "IT commission. Design visualisation / render.",
      response: "A set of 3D visualisations for Wonese (World Networking Services), an IT/networking company office interior. The design pairs an exposed-ceiling industrial aesthetic, bare concrete soffits, ductwork and signature red conduit runs, with warm timber workstations, glazed cabin partitions and a striking red-and-black branded reception. Spaces shown include the entrance facade/glass storefront, reception, open-plan workstation floors with iMac desks and a motivational graphic wall, and a private cabin with city views.",
    },
    gallery: [
      { src: "/assets/projects/wonese-world-networking-services-office/g01.jpg", alt: "Private director's cabin with a warm timber desk, dark lounge sofa, board-formed concrete wall and floor-to-ceiling city views.", span: "full" },
      { src: "/assets/projects/wonese-world-networking-services-office/g02.jpg", alt: "Open-plan workstation floor with iMac desks, exposed red-conduit ceiling and a 'struggle today' motivational graphic wall.", span: "half" },
      { src: "/assets/projects/wonese-world-networking-services-office/g03.jpg", alt: "Industrial open office with timber-topped iMac benches, glazed cabins and signature exposed red services overhead.", span: "half" },
      { src: "/assets/projects/wonese-world-networking-services-office/g04.jpg", alt: "Glazed storefront entrance with frosted glass doors and the red WONESE, World Networking Services logo on a wood-clad pier.", span: "wide" },
    ],
    featured: false,
    order: 30,
    seo: { title: "Wonese, World Networking Services Office, Interior", description: "An industrial-modern office fit-out for an IT networking firm, blending exposed red services overhead with warm wood and a bold red-on-black brand identity" },
  },
];
